spring:
  application:
    name: eWallet
  servlet:
    multipart:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/ewallet_db
    username: postgres
    password: password123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: eWalletSuperSecretKeyForJwtSigningMustBeAtLeast256BitsLong2026UET
  expiration-ms: 86400000

server:
  port: 8081