package uet.com.eWallet.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import uet.com.eWallet.api.dto.request.RegisterRequest;
import uet.com.eWallet.api.dto.response.UserResponse;
import uet.com.eWallet.data.entity.User;

// componentModel = "spring" allows you to @Autowired this mapper in Spring components
@Mapper(componentModel = "spring")
public interface UserMapper {

    // 1. Convert from Entity (Database) to Response DTO (Client)
    UserResponse toUserResponse(User user);

    // 2. Convert from Request DTO (Client) to Entity (Database)
    // ID is auto-generated by the database, so we ignore it during creation
    @Mapping(target = "id", ignore = true)
    User toUser(RegisterRequest request);

}
